//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace PiXeL_Apps.WebserviceRef {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializableKeyValuePair", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiXeL_Apps.WebserviceRef.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiXeL_Apps.WebserviceRef.ArrayOfBase64Binary))]
    public partial class SerializableKeyValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBase64Binary", Namespace="http://tempuri.org/", ItemName="base64Binary")]
    public class ArrayOfBase64Binary : System.Collections.Generic.List<byte[]> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebserviceRef.PixelAppsWebserviceSoap")]
    public interface PixelAppsWebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetBrands", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetBrandsResponse> SQLite_GetBrandsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetBrandsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetDefectcodes", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesResponse> SQLite_GetDefectcodesAsync(PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetEenheiden", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenResponse> SQLite_GetEenheidenAsync(PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetEngines", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetEnginesResponse> SQLite_GetEnginesAsync(PiXeL_Apps.WebserviceRef.SQLite_GetEnginesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetFuels", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetFuelsResponse> SQLite_GetFuelsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetFuelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetScripts", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetScriptsResponse> SQLite_GetScriptsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetScriptsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetUsersResponse> SQLite_GetUsersAsync(PiXeL_Apps.WebserviceRef.SQLite_GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetVehicles", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesResponse> SQLite_GetVehiclesAsync(PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetObjectCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesResponse> SQLite_GetObjectCodesAsync(PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetComments", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetCommentsResponse> SQLite_GetCommentsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetCommentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SQLite_GetTransmissions", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsResponse> SQLite_GetTransmissionsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MaakCSV", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.MaakCSVResponse> MaakCSVAsync(PiXeL_Apps.WebserviceRef.MaakCSVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MaakCSVUSB", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.MaakCSVUSBResponse> MaakCSVUSBAsync(PiXeL_Apps.WebserviceRef.MaakCSVUSBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SynchroniseerVanUSB", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBResponse> SynchroniseerVanUSBAsync(PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/haalPdfBestandenOp", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfBestandenOpResponse> haalPdfBestandenOpAsync(PiXeL_Apps.WebserviceRef.haalPdfBestandenOpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/haalPdfNamenOp", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfNamenOpResponse> haalPdfNamenOpAsync(PiXeL_Apps.WebserviceRef.haalPdfNamenOpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/haalPdfWijzigingsdataOp", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpResponse> haalPdfWijzigingsdataOpAsync(PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeesExcel", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.LeesExcelResponse> LeesExcelAsync(PiXeL_Apps.WebserviceRef.LeesExcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZetConnectieString", ReplyAction="*")]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.ZetConnectieStringResponse> ZetConnectieStringAsync(PiXeL_Apps.WebserviceRef.ZetConnectieStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetBrandsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetBrands", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetBrandsRequestBody Body;
        
        public SQLite_GetBrandsRequest() {
        }
        
        public SQLite_GetBrandsRequest(PiXeL_Apps.WebserviceRef.SQLite_GetBrandsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetBrandsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int brandId;
        
        public SQLite_GetBrandsRequestBody() {
        }
        
        public SQLite_GetBrandsRequestBody(int brandId) {
            this.brandId = brandId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetBrandsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetBrandsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetBrandsResponseBody Body;
        
        public SQLite_GetBrandsResponse() {
        }
        
        public SQLite_GetBrandsResponse(PiXeL_Apps.WebserviceRef.SQLite_GetBrandsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetBrandsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetBrandsResult;
        
        public SQLite_GetBrandsResponseBody() {
        }
        
        public SQLite_GetBrandsResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetBrandsResult) {
            this.SQLite_GetBrandsResult = SQLite_GetBrandsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetDefectcodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetDefectcodes", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesRequestBody Body;
        
        public SQLite_GetDefectcodesRequest() {
        }
        
        public SQLite_GetDefectcodesRequest(PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SQLite_GetDefectcodesRequestBody {
        
        public SQLite_GetDefectcodesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetDefectcodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetDefectcodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesResponseBody Body;
        
        public SQLite_GetDefectcodesResponse() {
        }
        
        public SQLite_GetDefectcodesResponse(PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetDefectcodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetDefectcodesResult;
        
        public SQLite_GetDefectcodesResponseBody() {
        }
        
        public SQLite_GetDefectcodesResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetDefectcodesResult) {
            this.SQLite_GetDefectcodesResult = SQLite_GetDefectcodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetEenheidenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetEenheiden", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenRequestBody Body;
        
        public SQLite_GetEenheidenRequest() {
        }
        
        public SQLite_GetEenheidenRequest(PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetEenheidenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int eenheidId;
        
        public SQLite_GetEenheidenRequestBody() {
        }
        
        public SQLite_GetEenheidenRequestBody(int eenheidId) {
            this.eenheidId = eenheidId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetEenheidenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetEenheidenResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenResponseBody Body;
        
        public SQLite_GetEenheidenResponse() {
        }
        
        public SQLite_GetEenheidenResponse(PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetEenheidenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetEenheidenResult;
        
        public SQLite_GetEenheidenResponseBody() {
        }
        
        public SQLite_GetEenheidenResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetEenheidenResult) {
            this.SQLite_GetEenheidenResult = SQLite_GetEenheidenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetEnginesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetEngines", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetEnginesRequestBody Body;
        
        public SQLite_GetEnginesRequest() {
        }
        
        public SQLite_GetEnginesRequest(PiXeL_Apps.WebserviceRef.SQLite_GetEnginesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetEnginesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int engineId;
        
        public SQLite_GetEnginesRequestBody() {
        }
        
        public SQLite_GetEnginesRequestBody(int engineId) {
            this.engineId = engineId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetEnginesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetEnginesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetEnginesResponseBody Body;
        
        public SQLite_GetEnginesResponse() {
        }
        
        public SQLite_GetEnginesResponse(PiXeL_Apps.WebserviceRef.SQLite_GetEnginesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetEnginesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetEnginesResult;
        
        public SQLite_GetEnginesResponseBody() {
        }
        
        public SQLite_GetEnginesResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetEnginesResult) {
            this.SQLite_GetEnginesResult = SQLite_GetEnginesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetFuelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetFuels", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetFuelsRequestBody Body;
        
        public SQLite_GetFuelsRequest() {
        }
        
        public SQLite_GetFuelsRequest(PiXeL_Apps.WebserviceRef.SQLite_GetFuelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetFuelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int fuelId;
        
        public SQLite_GetFuelsRequestBody() {
        }
        
        public SQLite_GetFuelsRequestBody(int fuelId) {
            this.fuelId = fuelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetFuelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetFuelsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetFuelsResponseBody Body;
        
        public SQLite_GetFuelsResponse() {
        }
        
        public SQLite_GetFuelsResponse(PiXeL_Apps.WebserviceRef.SQLite_GetFuelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetFuelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetFuelsResult;
        
        public SQLite_GetFuelsResponseBody() {
        }
        
        public SQLite_GetFuelsResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetFuelsResult) {
            this.SQLite_GetFuelsResult = SQLite_GetFuelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetScriptsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetScripts", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetScriptsRequestBody Body;
        
        public SQLite_GetScriptsRequest() {
        }
        
        public SQLite_GetScriptsRequest(PiXeL_Apps.WebserviceRef.SQLite_GetScriptsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetScriptsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Vehicle_Id;
        
        public SQLite_GetScriptsRequestBody() {
        }
        
        public SQLite_GetScriptsRequestBody(string Vehicle_Id) {
            this.Vehicle_Id = Vehicle_Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetScriptsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetScriptsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetScriptsResponseBody Body;
        
        public SQLite_GetScriptsResponse() {
        }
        
        public SQLite_GetScriptsResponse(PiXeL_Apps.WebserviceRef.SQLite_GetScriptsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetScriptsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetScriptsResult;
        
        public SQLite_GetScriptsResponseBody() {
        }
        
        public SQLite_GetScriptsResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetScriptsResult) {
            this.SQLite_GetScriptsResult = SQLite_GetScriptsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetUsersRequestBody Body;
        
        public SQLite_GetUsersRequest() {
        }
        
        public SQLite_GetUsersRequest(PiXeL_Apps.WebserviceRef.SQLite_GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SQLite_GetUsersRequestBody {
        
        public SQLite_GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetUsersResponseBody Body;
        
        public SQLite_GetUsersResponse() {
        }
        
        public SQLite_GetUsersResponse(PiXeL_Apps.WebserviceRef.SQLite_GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetUsersResult;
        
        public SQLite_GetUsersResponseBody() {
        }
        
        public SQLite_GetUsersResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetUsersResult) {
            this.SQLite_GetUsersResult = SQLite_GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetVehiclesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetVehicles", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesRequestBody Body;
        
        public SQLite_GetVehiclesRequest() {
        }
        
        public SQLite_GetVehiclesRequest(PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SQLite_GetVehiclesRequestBody {
        
        public SQLite_GetVehiclesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetVehiclesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesResponseBody Body;
        
        public SQLite_GetVehiclesResponse() {
        }
        
        public SQLite_GetVehiclesResponse(PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetVehiclesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetVehiclesResult;
        
        public SQLite_GetVehiclesResponseBody() {
        }
        
        public SQLite_GetVehiclesResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetVehiclesResult) {
            this.SQLite_GetVehiclesResult = SQLite_GetVehiclesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetObjectCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetObjectCodes", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesRequestBody Body;
        
        public SQLite_GetObjectCodesRequest() {
        }
        
        public SQLite_GetObjectCodesRequest(PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SQLite_GetObjectCodesRequestBody {
        
        public SQLite_GetObjectCodesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetObjectCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetObjectCodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesResponseBody Body;
        
        public SQLite_GetObjectCodesResponse() {
        }
        
        public SQLite_GetObjectCodesResponse(PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetObjectCodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetObjectCodesResult;
        
        public SQLite_GetObjectCodesResponseBody() {
        }
        
        public SQLite_GetObjectCodesResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetObjectCodesResult) {
            this.SQLite_GetObjectCodesResult = SQLite_GetObjectCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetComments", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetCommentsRequestBody Body;
        
        public SQLite_GetCommentsRequest() {
        }
        
        public SQLite_GetCommentsRequest(PiXeL_Apps.WebserviceRef.SQLite_GetCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SQLite_GetCommentsRequestBody {
        
        public SQLite_GetCommentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetCommentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetCommentsResponseBody Body;
        
        public SQLite_GetCommentsResponse() {
        }
        
        public SQLite_GetCommentsResponse(PiXeL_Apps.WebserviceRef.SQLite_GetCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetCommentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetCommentsResult;
        
        public SQLite_GetCommentsResponseBody() {
        }
        
        public SQLite_GetCommentsResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetCommentsResult) {
            this.SQLite_GetCommentsResult = SQLite_GetCommentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetTransmissionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetTransmissions", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsRequestBody Body;
        
        public SQLite_GetTransmissionsRequest() {
        }
        
        public SQLite_GetTransmissionsRequest(PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetTransmissionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int transmissionId;
        
        public SQLite_GetTransmissionsRequestBody() {
        }
        
        public SQLite_GetTransmissionsRequestBody(int transmissionId) {
            this.transmissionId = transmissionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SQLite_GetTransmissionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SQLite_GetTransmissionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsResponseBody Body;
        
        public SQLite_GetTransmissionsResponse() {
        }
        
        public SQLite_GetTransmissionsResponse(PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SQLite_GetTransmissionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetTransmissionsResult;
        
        public SQLite_GetTransmissionsResponseBody() {
        }
        
        public SQLite_GetTransmissionsResponseBody(System.Collections.Generic.List<System.Collections.Generic.List<PiXeL_Apps.WebserviceRef.SerializableKeyValuePair>> SQLite_GetTransmissionsResult) {
            this.SQLite_GetTransmissionsResult = SQLite_GetTransmissionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaakCSVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MaakCSV", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.MaakCSVRequestBody Body;
        
        public MaakCSVRequest() {
        }
        
        public MaakCSVRequest(PiXeL_Apps.WebserviceRef.MaakCSVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MaakCSVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PiXeL_Apps.WebserviceRef.ArrayOfString lijstGegevens;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bestandsnaam;
        
        public MaakCSVRequestBody() {
        }
        
        public MaakCSVRequestBody(PiXeL_Apps.WebserviceRef.ArrayOfString lijstGegevens, string bestandsnaam) {
            this.lijstGegevens = lijstGegevens;
            this.bestandsnaam = bestandsnaam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaakCSVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MaakCSVResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.MaakCSVResponseBody Body;
        
        public MaakCSVResponse() {
        }
        
        public MaakCSVResponse(PiXeL_Apps.WebserviceRef.MaakCSVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MaakCSVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MaakCSVResult;
        
        public MaakCSVResponseBody() {
        }
        
        public MaakCSVResponseBody(bool MaakCSVResult) {
            this.MaakCSVResult = MaakCSVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaakCSVUSBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MaakCSVUSB", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.MaakCSVUSBRequestBody Body;
        
        public MaakCSVUSBRequest() {
        }
        
        public MaakCSVUSBRequest(PiXeL_Apps.WebserviceRef.MaakCSVUSBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MaakCSVUSBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PiXeL_Apps.WebserviceRef.ArrayOfString lijstGegevens;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bestandsnaam;
        
        public MaakCSVUSBRequestBody() {
        }
        
        public MaakCSVUSBRequestBody(PiXeL_Apps.WebserviceRef.ArrayOfString lijstGegevens, string bestandsnaam) {
            this.lijstGegevens = lijstGegevens;
            this.bestandsnaam = bestandsnaam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaakCSVUSBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MaakCSVUSBResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.MaakCSVUSBResponseBody Body;
        
        public MaakCSVUSBResponse() {
        }
        
        public MaakCSVUSBResponse(PiXeL_Apps.WebserviceRef.MaakCSVUSBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MaakCSVUSBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MaakCSVUSBResult;
        
        public MaakCSVUSBResponseBody() {
        }
        
        public MaakCSVUSBResponseBody(bool MaakCSVUSBResult) {
            this.MaakCSVUSBResult = MaakCSVUSBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SynchroniseerVanUSBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SynchroniseerVanUSB", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBRequestBody Body;
        
        public SynchroniseerVanUSBRequest() {
        }
        
        public SynchroniseerVanUSBRequest(PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SynchroniseerVanUSBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wagennummer;
        
        public SynchroniseerVanUSBRequestBody() {
        }
        
        public SynchroniseerVanUSBRequestBody(string wagennummer) {
            this.wagennummer = wagennummer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SynchroniseerVanUSBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SynchroniseerVanUSBResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBResponseBody Body;
        
        public SynchroniseerVanUSBResponse() {
        }
        
        public SynchroniseerVanUSBResponse(PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SynchroniseerVanUSBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SynchroniseerVanUSBResult;
        
        public SynchroniseerVanUSBResponseBody() {
        }
        
        public SynchroniseerVanUSBResponseBody(bool SynchroniseerVanUSBResult) {
            this.SynchroniseerVanUSBResult = SynchroniseerVanUSBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class haalPdfBestandenOpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="haalPdfBestandenOp", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.haalPdfBestandenOpRequestBody Body;
        
        public haalPdfBestandenOpRequest() {
        }
        
        public haalPdfBestandenOpRequest(PiXeL_Apps.WebserviceRef.haalPdfBestandenOpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class haalPdfBestandenOpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vehicle_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PiXeL_Apps.WebserviceRef.ArrayOfString pdfNamen;
        
        public haalPdfBestandenOpRequestBody() {
        }
        
        public haalPdfBestandenOpRequestBody(string vehicle_id, PiXeL_Apps.WebserviceRef.ArrayOfString pdfNamen) {
            this.vehicle_id = vehicle_id;
            this.pdfNamen = pdfNamen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class haalPdfBestandenOpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="haalPdfBestandenOpResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.haalPdfBestandenOpResponseBody Body;
        
        public haalPdfBestandenOpResponse() {
        }
        
        public haalPdfBestandenOpResponse(PiXeL_Apps.WebserviceRef.haalPdfBestandenOpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class haalPdfBestandenOpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PiXeL_Apps.WebserviceRef.ArrayOfBase64Binary haalPdfBestandenOpResult;
        
        public haalPdfBestandenOpResponseBody() {
        }
        
        public haalPdfBestandenOpResponseBody(PiXeL_Apps.WebserviceRef.ArrayOfBase64Binary haalPdfBestandenOpResult) {
            this.haalPdfBestandenOpResult = haalPdfBestandenOpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class haalPdfNamenOpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="haalPdfNamenOp", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.haalPdfNamenOpRequestBody Body;
        
        public haalPdfNamenOpRequest() {
        }
        
        public haalPdfNamenOpRequest(PiXeL_Apps.WebserviceRef.haalPdfNamenOpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class haalPdfNamenOpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vehicle_id;
        
        public haalPdfNamenOpRequestBody() {
        }
        
        public haalPdfNamenOpRequestBody(string vehicle_id) {
            this.vehicle_id = vehicle_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class haalPdfNamenOpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="haalPdfNamenOpResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.haalPdfNamenOpResponseBody Body;
        
        public haalPdfNamenOpResponse() {
        }
        
        public haalPdfNamenOpResponse(PiXeL_Apps.WebserviceRef.haalPdfNamenOpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class haalPdfNamenOpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PiXeL_Apps.WebserviceRef.ArrayOfString haalPdfNamenOpResult;
        
        public haalPdfNamenOpResponseBody() {
        }
        
        public haalPdfNamenOpResponseBody(PiXeL_Apps.WebserviceRef.ArrayOfString haalPdfNamenOpResult) {
            this.haalPdfNamenOpResult = haalPdfNamenOpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class haalPdfWijzigingsdataOpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="haalPdfWijzigingsdataOp", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpRequestBody Body;
        
        public haalPdfWijzigingsdataOpRequest() {
        }
        
        public haalPdfWijzigingsdataOpRequest(PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class haalPdfWijzigingsdataOpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vehicle_id;
        
        public haalPdfWijzigingsdataOpRequestBody() {
        }
        
        public haalPdfWijzigingsdataOpRequestBody(string vehicle_id) {
            this.vehicle_id = vehicle_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class haalPdfWijzigingsdataOpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="haalPdfWijzigingsdataOpResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpResponseBody Body;
        
        public haalPdfWijzigingsdataOpResponse() {
        }
        
        public haalPdfWijzigingsdataOpResponse(PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class haalPdfWijzigingsdataOpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PiXeL_Apps.WebserviceRef.ArrayOfString haalPdfWijzigingsdataOpResult;
        
        public haalPdfWijzigingsdataOpResponseBody() {
        }
        
        public haalPdfWijzigingsdataOpResponseBody(PiXeL_Apps.WebserviceRef.ArrayOfString haalPdfWijzigingsdataOpResult) {
            this.haalPdfWijzigingsdataOpResult = haalPdfWijzigingsdataOpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeesExcelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeesExcel", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.LeesExcelRequestBody Body;
        
        public LeesExcelRequest() {
        }
        
        public LeesExcelRequest(PiXeL_Apps.WebserviceRef.LeesExcelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LeesExcelRequestBody {
        
        public LeesExcelRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeesExcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeesExcelResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.LeesExcelResponseBody Body;
        
        public LeesExcelResponse() {
        }
        
        public LeesExcelResponse(PiXeL_Apps.WebserviceRef.LeesExcelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeesExcelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PiXeL_Apps.WebserviceRef.ArrayOfString LeesExcelResult;
        
        public LeesExcelResponseBody() {
        }
        
        public LeesExcelResponseBody(PiXeL_Apps.WebserviceRef.ArrayOfString LeesExcelResult) {
            this.LeesExcelResult = LeesExcelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZetConnectieStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZetConnectieString", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.ZetConnectieStringRequestBody Body;
        
        public ZetConnectieStringRequest() {
        }
        
        public ZetConnectieStringRequest(PiXeL_Apps.WebserviceRef.ZetConnectieStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZetConnectieStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pad;
        
        public ZetConnectieStringRequestBody() {
        }
        
        public ZetConnectieStringRequestBody(string pad) {
            this.pad = pad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZetConnectieStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZetConnectieStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public PiXeL_Apps.WebserviceRef.ZetConnectieStringResponseBody Body;
        
        public ZetConnectieStringResponse() {
        }
        
        public ZetConnectieStringResponse(PiXeL_Apps.WebserviceRef.ZetConnectieStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ZetConnectieStringResponseBody {
        
        public ZetConnectieStringResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PixelAppsWebserviceSoapChannel : PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PixelAppsWebserviceSoapClient : System.ServiceModel.ClientBase<PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap>, PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PixelAppsWebserviceSoapClient() : 
                base(PixelAppsWebserviceSoapClient.GetDefaultBinding(), PixelAppsWebserviceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.PixelAppsWebserviceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PixelAppsWebserviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PixelAppsWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), PixelAppsWebserviceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PixelAppsWebserviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PixelAppsWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PixelAppsWebserviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PixelAppsWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PixelAppsWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetBrandsResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetBrandsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetBrandsRequest request) {
            return base.Channel.SQLite_GetBrandsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetBrandsResponse> SQLite_GetBrandsAsync(int brandId) {
            PiXeL_Apps.WebserviceRef.SQLite_GetBrandsRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetBrandsRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetBrandsRequestBody();
            inValue.Body.brandId = brandId;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetBrandsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetDefectcodesAsync(PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesRequest request) {
            return base.Channel.SQLite_GetDefectcodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesResponse> SQLite_GetDefectcodesAsync() {
            PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetDefectcodesRequestBody();
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetDefectcodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetEenheidenAsync(PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenRequest request) {
            return base.Channel.SQLite_GetEenheidenAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenResponse> SQLite_GetEenheidenAsync(int eenheidId) {
            PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetEenheidenRequestBody();
            inValue.Body.eenheidId = eenheidId;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetEenheidenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetEnginesResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetEnginesAsync(PiXeL_Apps.WebserviceRef.SQLite_GetEnginesRequest request) {
            return base.Channel.SQLite_GetEnginesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetEnginesResponse> SQLite_GetEnginesAsync(int engineId) {
            PiXeL_Apps.WebserviceRef.SQLite_GetEnginesRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetEnginesRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetEnginesRequestBody();
            inValue.Body.engineId = engineId;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetEnginesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetFuelsResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetFuelsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetFuelsRequest request) {
            return base.Channel.SQLite_GetFuelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetFuelsResponse> SQLite_GetFuelsAsync(int fuelId) {
            PiXeL_Apps.WebserviceRef.SQLite_GetFuelsRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetFuelsRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetFuelsRequestBody();
            inValue.Body.fuelId = fuelId;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetFuelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetScriptsResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetScriptsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetScriptsRequest request) {
            return base.Channel.SQLite_GetScriptsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetScriptsResponse> SQLite_GetScriptsAsync(string Vehicle_Id) {
            PiXeL_Apps.WebserviceRef.SQLite_GetScriptsRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetScriptsRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetScriptsRequestBody();
            inValue.Body.Vehicle_Id = Vehicle_Id;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetScriptsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetUsersResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetUsersAsync(PiXeL_Apps.WebserviceRef.SQLite_GetUsersRequest request) {
            return base.Channel.SQLite_GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetUsersResponse> SQLite_GetUsersAsync() {
            PiXeL_Apps.WebserviceRef.SQLite_GetUsersRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetUsersRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetUsersRequestBody();
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetVehiclesAsync(PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesRequest request) {
            return base.Channel.SQLite_GetVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesResponse> SQLite_GetVehiclesAsync() {
            PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetVehiclesRequestBody();
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetVehiclesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetObjectCodesAsync(PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesRequest request) {
            return base.Channel.SQLite_GetObjectCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesResponse> SQLite_GetObjectCodesAsync() {
            PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetObjectCodesRequestBody();
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetObjectCodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetCommentsResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetCommentsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetCommentsRequest request) {
            return base.Channel.SQLite_GetCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetCommentsResponse> SQLite_GetCommentsAsync() {
            PiXeL_Apps.WebserviceRef.SQLite_GetCommentsRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetCommentsRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetCommentsRequestBody();
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SQLite_GetTransmissionsAsync(PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsRequest request) {
            return base.Channel.SQLite_GetTransmissionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsResponse> SQLite_GetTransmissionsAsync(int transmissionId) {
            PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsRequest inValue = new PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SQLite_GetTransmissionsRequestBody();
            inValue.Body.transmissionId = transmissionId;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SQLite_GetTransmissionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.MaakCSVResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.MaakCSVAsync(PiXeL_Apps.WebserviceRef.MaakCSVRequest request) {
            return base.Channel.MaakCSVAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.MaakCSVResponse> MaakCSVAsync(PiXeL_Apps.WebserviceRef.ArrayOfString lijstGegevens, string bestandsnaam) {
            PiXeL_Apps.WebserviceRef.MaakCSVRequest inValue = new PiXeL_Apps.WebserviceRef.MaakCSVRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.MaakCSVRequestBody();
            inValue.Body.lijstGegevens = lijstGegevens;
            inValue.Body.bestandsnaam = bestandsnaam;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).MaakCSVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.MaakCSVUSBResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.MaakCSVUSBAsync(PiXeL_Apps.WebserviceRef.MaakCSVUSBRequest request) {
            return base.Channel.MaakCSVUSBAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.MaakCSVUSBResponse> MaakCSVUSBAsync(PiXeL_Apps.WebserviceRef.ArrayOfString lijstGegevens, string bestandsnaam) {
            PiXeL_Apps.WebserviceRef.MaakCSVUSBRequest inValue = new PiXeL_Apps.WebserviceRef.MaakCSVUSBRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.MaakCSVUSBRequestBody();
            inValue.Body.lijstGegevens = lijstGegevens;
            inValue.Body.bestandsnaam = bestandsnaam;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).MaakCSVUSBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.SynchroniseerVanUSBAsync(PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBRequest request) {
            return base.Channel.SynchroniseerVanUSBAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBResponse> SynchroniseerVanUSBAsync(string wagennummer) {
            PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBRequest inValue = new PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.SynchroniseerVanUSBRequestBody();
            inValue.Body.wagennummer = wagennummer;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).SynchroniseerVanUSBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfBestandenOpResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.haalPdfBestandenOpAsync(PiXeL_Apps.WebserviceRef.haalPdfBestandenOpRequest request) {
            return base.Channel.haalPdfBestandenOpAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfBestandenOpResponse> haalPdfBestandenOpAsync(string vehicle_id, PiXeL_Apps.WebserviceRef.ArrayOfString pdfNamen) {
            PiXeL_Apps.WebserviceRef.haalPdfBestandenOpRequest inValue = new PiXeL_Apps.WebserviceRef.haalPdfBestandenOpRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.haalPdfBestandenOpRequestBody();
            inValue.Body.vehicle_id = vehicle_id;
            inValue.Body.pdfNamen = pdfNamen;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).haalPdfBestandenOpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfNamenOpResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.haalPdfNamenOpAsync(PiXeL_Apps.WebserviceRef.haalPdfNamenOpRequest request) {
            return base.Channel.haalPdfNamenOpAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfNamenOpResponse> haalPdfNamenOpAsync(string vehicle_id) {
            PiXeL_Apps.WebserviceRef.haalPdfNamenOpRequest inValue = new PiXeL_Apps.WebserviceRef.haalPdfNamenOpRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.haalPdfNamenOpRequestBody();
            inValue.Body.vehicle_id = vehicle_id;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).haalPdfNamenOpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.haalPdfWijzigingsdataOpAsync(PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpRequest request) {
            return base.Channel.haalPdfWijzigingsdataOpAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpResponse> haalPdfWijzigingsdataOpAsync(string vehicle_id) {
            PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpRequest inValue = new PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.haalPdfWijzigingsdataOpRequestBody();
            inValue.Body.vehicle_id = vehicle_id;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).haalPdfWijzigingsdataOpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.LeesExcelResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.LeesExcelAsync(PiXeL_Apps.WebserviceRef.LeesExcelRequest request) {
            return base.Channel.LeesExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.LeesExcelResponse> LeesExcelAsync() {
            PiXeL_Apps.WebserviceRef.LeesExcelRequest inValue = new PiXeL_Apps.WebserviceRef.LeesExcelRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.LeesExcelRequestBody();
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).LeesExcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.ZetConnectieStringResponse> PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap.ZetConnectieStringAsync(PiXeL_Apps.WebserviceRef.ZetConnectieStringRequest request) {
            return base.Channel.ZetConnectieStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<PiXeL_Apps.WebserviceRef.ZetConnectieStringResponse> ZetConnectieStringAsync(string pad) {
            PiXeL_Apps.WebserviceRef.ZetConnectieStringRequest inValue = new PiXeL_Apps.WebserviceRef.ZetConnectieStringRequest();
            inValue.Body = new PiXeL_Apps.WebserviceRef.ZetConnectieStringRequestBody();
            inValue.Body.pad = pad;
            return ((PiXeL_Apps.WebserviceRef.PixelAppsWebserviceSoap)(this)).ZetConnectieStringAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PixelAppsWebserviceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PixelAppsWebserviceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:52506/PixelAppsWebservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return PixelAppsWebserviceSoapClient.GetBindingForEndpoint(EndpointConfiguration.PixelAppsWebserviceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return PixelAppsWebserviceSoapClient.GetEndpointAddress(EndpointConfiguration.PixelAppsWebserviceSoap);
        }
        
        public enum EndpointConfiguration {
            
            PixelAppsWebserviceSoap,
        }
    }
}
